[package]
name = "eyes"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
clap.workspace = true
http.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thieving-eyes-protocol = { path = "../../crates/protocol" }
thieving-eyes-service = { path = "../../crates/service" }
thieving-eyes-runtime-sandbox-agent = { path = "../../crates/runtime-sandbox-agent" }
tokio.workspace = true
toml.workspace = true
ulid.workspace = true

[lints]
workspace = true
