export {
  ThievingEyesClient,
  ThievingEyesError,
  ThievingEyesProtocolError,
  defaultSocketPath,
  type RequestOptions,
  type RunOptions,
  type SubmitOptions,
  type ThievingEyesClientOptions,
  type WatchOptions,
} from "./client.js";

export type {
  AgentSelector,
  ApiError,
  ArtifactCollection,
  ArtifactRef,
  Attempt,
  Blocker,
  CancellationResult,
  CapabilityCatalog,
  CapabilityDescriptor,
  CapabilityRequirement,
  ContentPart,
  ErrorDetail,
  EventEnvelope,
  ExecutionSelector,
  ExtensionRef,
  FileRef,
  Input,
  JsonSchemaSource,
  Limits,
  ObjectRef,
  OutputSpec,
  OutputValue,
  Page,
  ResourceRef,
  ResourceSelector,
  ResourceSummary,
  RuntimeRef,
  Scheduling,
  SessionBinding,
  SubmissionAccepted,
  SubmissionCreate,
  SubmissionPatch,
  SubmissionResult,
  SubmissionState,
  SubmissionStatus,
  TaskMode,
  UsageSummary,
  WorkspaceAccess,
  WorkspaceRef,
} from "./schema.js";
