/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/capabilities": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get effective capabilities */
        readonly get: operations["getCapabilities"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/extensions": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List extensions */
        readonly get: operations["listExtensions"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/extensions/{extension_id}/versions/{version}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly extension_id: string;
                readonly version: string;
            };
            readonly cookie?: never;
        };
        /** Get an extension version */
        readonly get: operations["getExtension"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/policies": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List policies */
        readonly get: operations["listPolicies"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/policies/{policy_id}/versions/{version}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly policy_id: string;
                readonly version: string;
            };
            readonly cookie?: never;
        };
        /** Get a policy version */
        readonly get: operations["getPolicy"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/profiles": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List profiles */
        readonly get: operations["listProfiles"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/profiles/{profile_id}/versions/{version}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly profile_id: string;
                readonly version: string;
            };
            readonly cookie?: never;
        };
        /** Get a profile version */
        readonly get: operations["getProfile"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/sessions": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List sessions */
        readonly get: operations["listSessions"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/sessions/{session_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly session_id: string;
            };
            readonly cookie?: never;
        };
        /** Get a session */
        readonly get: operations["getSession"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/sessions/{session_id}/events": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly session_id: string;
            };
            readonly cookie?: never;
        };
        /** List session events */
        readonly get: operations["listSessionEvents"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/sessions/{session_id}/submissions": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly session_id: string;
            };
            readonly cookie?: never;
        };
        /** List session submissions */
        readonly get: operations["listSessionSubmissions"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/submissions": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List submissions */
        readonly get: operations["listSubmissions"];
        readonly put?: never;
        /** Create a durable submission */
        readonly post: operations["createSubmission"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/submissions/{submission_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly submission_id: components["parameters"]["SubmissionId"];
            };
            readonly cookie?: never;
        };
        /** Get submission status */
        readonly get: operations["getSubmission"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        /** Update queued scheduling constraints */
        readonly patch: operations["patchSubmission"];
        readonly trace?: never;
    };
    readonly "/submissions/{submission_id}/cancel": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly submission_id: components["parameters"]["SubmissionId"];
            };
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Request submission cancellation */
        readonly post: operations["cancelSubmission"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/submissions/{submission_id}/events": {
        readonly parameters: {
            readonly query?: {
                readonly after_sequence?: number;
            };
            readonly header?: never;
            readonly path: {
                readonly submission_id: components["parameters"]["SubmissionId"];
            };
            readonly cookie?: never;
        };
        /** Watch persistent submission events */
        readonly get: operations["watchSubmissionEvents"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/submissions/{submission_id}/result": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly submission_id: components["parameters"]["SubmissionId"];
            };
            readonly cookie?: never;
        };
        /** Get a terminal submission result */
        readonly get: operations["getSubmissionResult"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        readonly AgentSelector: {
            readonly adapter?: string;
            readonly extensions?: readonly components["schemas"]["ExtensionRef"][];
            readonly model?: string;
            readonly profile?: components["schemas"]["ResourceSelector"];
            readonly required_capabilities?: readonly components["schemas"]["CapabilityRequirement"][];
        };
        readonly ApiError: {
            readonly error: components["schemas"]["ErrorDetail"];
            readonly request_id: string;
        };
        readonly ArtifactCollection: {
            readonly include: readonly string[];
            readonly sink_id: string;
        };
        readonly ArtifactRef: {
            readonly digest: string;
            readonly media_type: string;
            readonly object_key: string;
            readonly sink_id: string;
            readonly size_bytes: number;
        };
        readonly Attempt: {
            readonly adapter: string;
            readonly agent_version?: string;
            readonly attempt_id: string;
            readonly error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            readonly finished_at?: string;
            readonly model: string;
            readonly number: number;
            readonly route_id: string;
            readonly runtime: components["schemas"]["RuntimeRef"];
            readonly sandbox_profile: string;
            readonly session_id?: string;
            readonly source_label: string;
            /** Format: date-time */
            readonly started_at?: string;
            /** @enum {unknown} */
            readonly state: "starting" | "running" | "completed" | "failed" | "cancelled" | "uncertain";
            readonly target_id: string;
            readonly usage?: components["schemas"]["UsageSummary"];
        };
        readonly Blocker: {
            readonly code: string;
            readonly detail?: string;
            /** Format: date-time */
            readonly retry_after?: string;
        };
        readonly CancellationResult: {
            /** @enum {unknown} */
            readonly disposition: "cancelled" | "cancellation_requested" | "already_terminal" | "delivery_unknown";
            readonly revision: number;
            readonly submission_id: string;
        };
        readonly CapabilityCatalog: {
            readonly capabilities: readonly components["schemas"]["CapabilityDescriptor"][];
        };
        readonly CapabilityDescriptor: {
            readonly constraints?: {
                readonly [key: string]: unknown;
            };
            readonly name: string;
            readonly version: string;
        };
        readonly CapabilityRequirement: {
            readonly min_version?: string;
            readonly name: string;
        };
        readonly ContentPart: {
            readonly text: string;
            /** @constant */
            readonly type: "text";
        } | {
            readonly data: unknown;
            readonly media_type?: string;
            /** @constant */
            readonly type: "data";
        } | {
            readonly file: components["schemas"]["FileRef"];
            readonly media_type?: string;
            readonly name?: string;
            /** @constant */
            readonly type: "file";
        };
        readonly ErrorDetail: {
            readonly code: string;
            readonly field?: string;
            readonly message: string;
            readonly retry_after_seconds?: number;
            readonly retryable: boolean;
            /** @enum {unknown} */
            readonly scope: "request" | "submission" | "attempt" | "route" | "target" | "source" | "session";
        };
        readonly EventEnvelope: {
            readonly attempt_id?: string;
            readonly data: {
                readonly [key: string]: unknown;
            };
            readonly event_id: string;
            /** Format: date-time */
            readonly occurred_at: string;
            readonly sequence: number;
            readonly session_id?: string;
            readonly submission_id: string;
            readonly type: string;
        };
        readonly ExecutionSelector: {
            /** @enum {unknown} */
            readonly locality?: "local_only" | "any";
            readonly route_ids?: readonly string[];
            /** @enum {unknown} */
            readonly side_effects?: "read_only" | "idempotent_write" | "side_effecting";
            readonly target_ids?: readonly string[];
        };
        readonly ExtensionRef: {
            /** @enum {unknown} */
            readonly kind: "skill" | "mcp" | "plugin";
            readonly resource: components["schemas"]["ResourceSelector"];
        };
        readonly FileRef: {
            readonly digest?: string;
            /** @constant */
            readonly kind: "workspace";
            readonly path: string;
        } | {
            /** @constant */
            readonly kind: "object";
            readonly object: components["schemas"]["ObjectRef"];
        };
        readonly Input: {
            readonly parts: readonly components["schemas"]["ContentPart"][];
        };
        readonly JsonSchemaSource: {
            /** @constant */
            readonly kind: "inline";
            readonly value: unknown;
        } | {
            /** @constant */
            readonly kind: "object";
            readonly object: components["schemas"]["ObjectRef"];
        };
        readonly Limits: {
            readonly idle_timeout_seconds?: number;
            readonly max_provider_requests?: number;
            readonly max_tokens?: number;
            readonly run_timeout_seconds?: number;
        };
        readonly ObjectRef: {
            readonly digest: string;
            readonly media_type?: string;
            readonly object_key: string;
            readonly resolver_id: string;
            readonly size_bytes?: number;
        };
        readonly OutputSpec: {
            readonly artifacts?: components["schemas"]["ArtifactCollection"];
            readonly final?: {
                /** @constant */
                readonly kind: "text";
            } | {
                /** @constant */
                readonly kind: "json_schema";
                readonly schema: components["schemas"]["JsonSchemaSource"];
            };
        };
        readonly OutputValue: {
            /** @constant */
            readonly kind: "text";
            readonly text: string;
            readonly truncated: boolean;
        } | {
            readonly data: unknown;
            /** @constant */
            readonly kind: "data";
        };
        readonly Page: {
            readonly items: readonly unknown[];
            readonly next_cursor: string | null;
        };
        readonly ResourceRef: {
            readonly digest: string;
            readonly id: string;
            readonly version: string;
        };
        readonly ResourceSelector: {
            readonly id: string;
            readonly version?: string;
        };
        readonly ResourceSummary: {
            readonly capabilities: readonly components["schemas"]["CapabilityDescriptor"][];
            readonly deprecated: boolean;
            readonly description?: string;
            readonly ref: components["schemas"]["ResourceRef"];
        };
        readonly RuntimeRef: {
            readonly digest: string;
            /** @constant */
            readonly name: "sandbox-agent";
            readonly version: string;
        };
        readonly Scheduling: {
            /** Format: date-time */
            readonly not_before?: string;
            /** @default 50 */
            readonly priority?: number;
            /** Format: date-time */
            readonly start_deadline?: string;
        };
        readonly SessionBinding: {
            /** @constant */
            readonly mode: "ephemeral";
        } | {
            /** @constant */
            readonly mode: "create";
            readonly retention_seconds?: number;
        } | {
            /** @constant */
            readonly mode: "resume";
            readonly session_id: string;
        };
        readonly SubmissionAccepted: {
            readonly events_url: string;
            readonly idempotent_replay: boolean;
            readonly request_digest: string;
            readonly resolved_policy: components["schemas"]["ResourceRef"];
            readonly resolved_profile: components["schemas"]["ResourceRef"];
            readonly result_url: string;
            readonly revision: number;
            /** @constant */
            readonly state: "queued";
            readonly status_url: string;
            readonly submission_id: string;
            /** @constant */
            readonly terminal: false;
        };
        readonly SubmissionCreate: {
            readonly agent?: components["schemas"]["AgentSelector"];
            readonly client_reference?: string;
            readonly execution?: components["schemas"]["ExecutionSelector"];
            readonly input: components["schemas"]["Input"];
            readonly labels?: {
                readonly [key: string]: string;
            };
            readonly limits?: components["schemas"]["Limits"];
            readonly mode?: components["schemas"]["TaskMode"];
            readonly output?: components["schemas"]["OutputSpec"];
            readonly policy?: components["schemas"]["ResourceSelector"];
            readonly scheduling?: components["schemas"]["Scheduling"];
            readonly session?: components["schemas"]["SessionBinding"];
            readonly workspace?: components["schemas"]["WorkspaceRef"];
        };
        readonly SubmissionPatch: {
            /** Format: date-time */
            readonly not_before?: string | null;
            readonly priority?: number;
            /** Format: date-time */
            readonly start_deadline?: string | null;
        };
        readonly SubmissionResult: {
            readonly artifacts: readonly components["schemas"]["ArtifactRef"][];
            readonly attempts: readonly components["schemas"]["Attempt"][];
            readonly error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            readonly finished_at: string;
            readonly output?: components["schemas"]["OutputValue"];
            readonly state: components["schemas"]["SubmissionState"];
            readonly submission_id: string;
            /** @constant */
            readonly terminal: true;
            readonly usage?: components["schemas"]["UsageSummary"];
        };
        /** @enum {unknown} */
        readonly SubmissionState: "queued" | "running" | "completed" | "failed" | "cancelled" | "expired" | "uncertain";
        readonly SubmissionStatus: {
            readonly attempts: readonly components["schemas"]["Attempt"][];
            readonly blocker?: components["schemas"]["Blocker"];
            readonly client_reference?: string;
            /** Format: date-time */
            readonly created_at: string;
            readonly error?: components["schemas"]["ErrorDetail"];
            readonly latest_event_sequence: number;
            /** @enum {unknown} */
            readonly mode: "task" | "goal";
            readonly request_digest: string;
            readonly resolved_policy: components["schemas"]["ResourceRef"];
            readonly resolved_profile: components["schemas"]["ResourceRef"];
            readonly revision: number;
            readonly session_id?: string;
            readonly state: components["schemas"]["SubmissionState"];
            readonly submission_id: string;
            readonly terminal: boolean;
            /** Format: date-time */
            readonly updated_at: string;
        };
        readonly TaskMode: {
            /** @constant */
            readonly kind: "task";
        } | {
            /** @constant */
            readonly kind: "goal";
            readonly token_budget?: number;
        };
        readonly UsageSummary: {
            readonly input_tokens?: number;
            readonly measurement: string;
            readonly output_tokens?: number;
            readonly provider_requests?: number;
            readonly reasoning_tokens?: number;
        };
        /** @enum {unknown} */
        readonly WorkspaceAccess: "read_only" | "writable" | "writable_overlay";
        readonly WorkspaceRef: {
            readonly access?: components["schemas"]["WorkspaceAccess"];
            /** @constant */
            readonly kind: "local";
            readonly path?: string;
            readonly revision?: string;
            readonly root_id: string;
        } | {
            /** @enum {unknown} */
            readonly access?: "read_only" | "writable_overlay";
            readonly binding_id: string;
            /** @constant */
            readonly kind: "binding";
            readonly revision: string;
        };
    };
    responses: {
        /** @description Empty page for an unsupported resource family */
        readonly EmptyPage: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["Page"];
            };
        };
        /** @description Stable API error */
        readonly Error: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Immutable resource version */
        readonly Resource: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ResourceSummary"];
            };
        };
        /** @description Resource page */
        readonly ResourcePage: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["Page"] & {
                    readonly items?: readonly components["schemas"]["ResourceSummary"][];
                };
            };
        };
        /** @description Accepted durable request */
        readonly SubmissionAccepted: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["SubmissionAccepted"];
            };
        };
    };
    parameters: {
        readonly SubmissionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type AgentSelector = components['schemas']['AgentSelector'];
export type ApiError = components['schemas']['ApiError'];
export type ArtifactCollection = components['schemas']['ArtifactCollection'];
export type ArtifactRef = components['schemas']['ArtifactRef'];
export type Attempt = components['schemas']['Attempt'];
export type Blocker = components['schemas']['Blocker'];
export type CancellationResult = components['schemas']['CancellationResult'];
export type CapabilityCatalog = components['schemas']['CapabilityCatalog'];
export type CapabilityDescriptor = components['schemas']['CapabilityDescriptor'];
export type CapabilityRequirement = components['schemas']['CapabilityRequirement'];
export type ContentPart = components['schemas']['ContentPart'];
export type ErrorDetail = components['schemas']['ErrorDetail'];
export type EventEnvelope = components['schemas']['EventEnvelope'];
export type ExecutionSelector = components['schemas']['ExecutionSelector'];
export type ExtensionRef = components['schemas']['ExtensionRef'];
export type FileRef = components['schemas']['FileRef'];
export type Input = components['schemas']['Input'];
export type JsonSchemaSource = components['schemas']['JsonSchemaSource'];
export type Limits = components['schemas']['Limits'];
export type ObjectRef = components['schemas']['ObjectRef'];
export type OutputSpec = components['schemas']['OutputSpec'];
export type OutputValue = components['schemas']['OutputValue'];
export type Page = components['schemas']['Page'];
export type ResourceRef = components['schemas']['ResourceRef'];
export type ResourceSelector = components['schemas']['ResourceSelector'];
export type ResourceSummary = components['schemas']['ResourceSummary'];
export type RuntimeRef = components['schemas']['RuntimeRef'];
export type Scheduling = components['schemas']['Scheduling'];
export type SessionBinding = components['schemas']['SessionBinding'];
export type SubmissionAccepted = components['schemas']['SubmissionAccepted'];
export type SubmissionCreate = components['schemas']['SubmissionCreate'];
export type SubmissionPatch = components['schemas']['SubmissionPatch'];
export type SubmissionResult = components['schemas']['SubmissionResult'];
export type SubmissionState = components['schemas']['SubmissionState'];
export type SubmissionStatus = components['schemas']['SubmissionStatus'];
export type TaskMode = components['schemas']['TaskMode'];
export type UsageSummary = components['schemas']['UsageSummary'];
export type WorkspaceAccess = components['schemas']['WorkspaceAccess'];
export type WorkspaceRef = components['schemas']['WorkspaceRef'];
export type ResponseEmptyPage = components['responses']['EmptyPage'];
export type ResponseError = components['responses']['Error'];
export type ResponseResource = components['responses']['Resource'];
export type ResponseResourcePage = components['responses']['ResourcePage'];
export type ResponseSubmissionAccepted = components['responses']['SubmissionAccepted'];
export type ParameterSubmissionId = components['parameters']['SubmissionId'];
export type $defs = Record<string, never>;
export interface operations {
    readonly getCapabilities: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly "4XX": components["responses"]["Error"];
            /** @description Effective capability catalog */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["CapabilityCatalog"];
                };
            };
        };
    };
    readonly listExtensions: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly "4XX": components["responses"]["Error"];
            readonly 200: components["responses"]["EmptyPage"];
        };
    };
    readonly getExtension: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly extension_id: string;
                readonly version: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly "4XX": components["responses"]["Error"];
            readonly default: components["responses"]["Error"];
        };
    };
    readonly listPolicies: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly "4XX": components["responses"]["Error"];
            readonly 200: components["responses"]["ResourcePage"];
        };
    };
    readonly getPolicy: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly policy_id: string;
                readonly version: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly "4XX": components["responses"]["Error"];
            readonly 200: components["responses"]["Resource"];
            readonly default: components["responses"]["Error"];
        };
    };
    readonly listProfiles: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly "4XX": components["responses"]["Error"];
            readonly 200: components["responses"]["ResourcePage"];
        };
    };
    readonly getProfile: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly profile_id: string;
                readonly version: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly "4XX": components["responses"]["Error"];
            readonly 200: components["responses"]["Resource"];
            readonly default: components["responses"]["Error"];
        };
    };
    readonly listSessions: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly "4XX": components["responses"]["Error"];
            readonly 200: components["responses"]["EmptyPage"];
        };
    };
    readonly getSession: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly session_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly "4XX": components["responses"]["Error"];
            readonly default: components["responses"]["Error"];
        };
    };
    readonly listSessionEvents: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly session_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly "4XX": components["responses"]["Error"];
            readonly 200: components["responses"]["EmptyPage"];
        };
    };
    readonly listSessionSubmissions: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly session_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly "4XX": components["responses"]["Error"];
            readonly 200: components["responses"]["EmptyPage"];
        };
    };
    readonly listSubmissions: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly "4XX": components["responses"]["Error"];
            /** @description Submission page */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Page"] & {
                        readonly items?: readonly components["schemas"]["SubmissionStatus"][];
                    };
                };
            };
        };
    };
    readonly createSubmission: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "Idempotency-Key": string;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["SubmissionCreate"];
            };
        };
        readonly responses: {
            readonly "4XX": components["responses"]["Error"];
            readonly 200: components["responses"]["SubmissionAccepted"];
            readonly 201: components["responses"]["SubmissionAccepted"];
            readonly default: components["responses"]["Error"];
        };
    };
    readonly getSubmission: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly submission_id: components["parameters"]["SubmissionId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly "4XX": components["responses"]["Error"];
            /** @description Current status */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SubmissionStatus"];
                };
            };
            readonly default: components["responses"]["Error"];
        };
    };
    readonly patchSubmission: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "If-Match": string;
            };
            readonly path: {
                readonly submission_id: components["parameters"]["SubmissionId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["SubmissionPatch"];
            };
        };
        readonly responses: {
            readonly "4XX": components["responses"]["Error"];
            /** @description Updated status */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SubmissionStatus"];
                };
            };
            readonly default: components["responses"]["Error"];
        };
    };
    readonly cancelSubmission: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly submission_id: components["parameters"]["SubmissionId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly "4XX": components["responses"]["Error"];
            /** @description Cancellation disposition */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["CancellationResult"];
                };
            };
            readonly default: components["responses"]["Error"];
        };
    };
    readonly watchSubmissionEvents: {
        readonly parameters: {
            readonly query?: {
                readonly after_sequence?: number;
            };
            readonly header?: never;
            readonly path: {
                readonly submission_id: components["parameters"]["SubmissionId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly "4XX": components["responses"]["Error"];
            /** @description Persistent event stream */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "text/event-stream": components["schemas"]["EventEnvelope"];
                };
            };
            readonly default: components["responses"]["Error"];
        };
    };
    readonly getSubmissionResult: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly submission_id: components["parameters"]["SubmissionId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly "4XX": components["responses"]["Error"];
            /** @description Terminal result */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SubmissionResult"];
                };
            };
            readonly default: components["responses"]["Error"];
        };
    };
}
